Final Update on Capstone
Alusp/book_an_appointment_back_end pull request #23
Opened 2023-01-20 16:18 UTC by Alusp

## The following was implemented in this PR:

### The link to the Front End: [here](https://github.com/samiullah997/book_an_appointment_front_end/pull/12)

- [ ] Set up the repository and use Gitflow.
- [ ] Use Postgres as our database
- [ ] The user logs in to the website, only by typing the Email and Password.
- [ ] Create routes for links to: Motorcycles.

> "Reserve" form.

> "My reservations".

> "Add motorcycle.

> "Delete motorcycle.

2023-01-20 18:01 UTC, vichuge reviewed
Hi dear student, 

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Suggested changes
_Check the comments under the review._

- It's looks like there's an improvement area on tests, I invite you to do this. 🐶 
````
Finished in 2.37 seconds (files took 1.82 seconds to load)
24 examples, 11 failures

Failed examples:

rspec ./spec/integration/bike_spec.rb:23 # Bike API /api/v1/bikes post Bike created returns a 201 response
rspec ./spec/integration/bike_spec.rb:31 # Bike API /api/v1/bikes post invalid request returns a 422 response
rspec ./spec/integration/bike_spec.rb:44 # Bike API /api/v1/bikes/{id} get name found returns a 200 response
rspec ./spec/integration/bike_spec.rb:65 # Bike API /api/v1/bikes/{id} get bike not found returns a 404 response
rspec ./spec/integration/reservation_spec.rb:20 # Reservation API /api/v1/reservations post reservation created returns a 201 response
rspec ./spec/integration/reservation_spec.rb:25 # Reservation API /api/v1/reservations post invalid request returns a 422 response
rspec ./spec/integration/reservation_spec.rb:38 # Reservation API /api/v1/reservations/{id} get name found returns a 200 response
rspec ./spec/integration/reservation_spec.rb:53 # Reservation API /api/v1/reservations/{id} get reservation not found returns a 404 response
rspec ./spec/integration/user_spec.rb:21 # User API /api/v1/users post User created returns a 201 response
rspec ./spec/integration/user_spec.rb:39 # User API /api/v1/users/{id} get name found returns a 200 response
rspec ./spec/integration/user_spec.rb:55 # User API /api/v1/users/{id} get user not found returns a 404 response
````
### Remember, the Front-end review is [here](https://github.com/samiullah997/book_an_appointment_front_end/pull/12)

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-20 18:01 UTC, vichuge commented on db/seeds.rb
> +Bike.create(name: "AlusineDA", bike_image: "https://imgd.aeplcdn.com/1280x720/n/cw/ec/43482/sp-125-right-front-three-quarte
- Here I could add a user before to anything. Because the bike and reservation creation needs a user. 🐱

2023-01-20 18:01 UTC, vichuge commented on app/models/reservation.rb
> +end
- It looks like you could improve the reservation model with relations and validations. 🐵

2023-01-20 18:01 UTC, vichuge commented on config/routes.rb
> +      resources :users
- I invite you to add only statements here, sometimes there are some endpoints you'll not use, this is an excellent tool to omit this. 🐔 

example: `resources :bikes only: %i[index show update delete]`

2023-01-21 09:37 UTC, Alusp commented on db/seeds.rb
> +Bike.create(name: "AlusineDA", bike_image: "https://imgd.aeplcdn.com/1280x720/n/cw/ec/43482/sp-125-right-front-three-quarte
True, that is why I added the value 1 to all Bikes user ids and reservation user id, but I have added the seed for User now

2023-01-21 09:42 UTC, Alusp commented on app/models/reservation.rb
> +end
True it totally skipped the mind, thanks, resolved

2023-01-21 09:44 UTC, Alusp commented on config/routes.rb
> +      resources :users
Thanks very much for Highlighting it, however, they have been added in each controllers instead as an alternative to being in the routes

2023-01-21 11:18 UTC, Meltrust requested changes
Hi @Alusp,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Most tests are passing✔️
-  API is working well✔️ 
-  Good readme ✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._

_I strongly recommend you take them into account as they can improve your final evaluation._





Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-01-21 11:18 UTC, Meltrust commented on spec/models/reservation_spec.rb
> +    expect(reservation).to be_valid
- [ ] You've improved most of the tests, however, these 2 are not passing:

![image](https://user-images.githubusercontent.com/57421823/213863010-28cd2583-3ac5-425c-83d8-b38506dd8048.png)

## Explanation

The expectations are flipped because both tests should expect an invalid input instead of a valid one.

## Solution

Just turn around the expectations by changing `to` to `not_to`:

```ruby
  it 'is not valid without a bike_id' do
    reservation = Reservation.new(valid_attributes.except(:bike_id))
    expect(reservation).not_to be_valid
  end
  it 'is not valid without a user_id' do
    reservation = Reservation.new(valid_attributes.except(:user_id))
    expect(reservation).not_to be_valid
```

That way, all your tests will pass 💪

2023-01-21 11:18 UTC, Meltrust commented on config/routes.rb
> +      resources :users
- [ ] OPTIONAL:  It really would be great to generate only the routes needed by using the `:except` or `only` options in your `resources` method calls.

## Explanation

When you use the `resources` method in the routes file without options, all the routes will be generated regardless of being used, and regardless of being called in the controllers or not.  There will be unused routes, and the app's performance will suffer.  This is especially true on enterprise-level code.  This is why in the industry, this is considered not a good practice. 

## Customized example and tips

```ruby
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  mount_devise_token_auth_for 'User', at: 'auth'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  namespace :api do
    namespace :v1 do
      resources :reservations, except: [:update, :edit]
      resources :bikes, except: :edit
      resources :users, except: [:update. :edit]
    end
  end
end
```

Since you are using most of the routes, the `except` option makes sense.

I'll leave this one as optional, however, I highly suggest you only generate the necessary routes for your project. 👍 

That way, your project will meet the highest industry standards. 💪 

_note:  This is just an example created using my own experience and effort, and this should not be deemed as the "official" solution to the matter in any way._

2023-01-21 11:31 UTC, Alusp commented on spec/models/reservation_spec.rb
> +    expect(reservation).to be_valid
Alright @Meltrust , thanks very much for pointing this out. I have fixed It.

2023-01-21 11:33 UTC, Alusp commented on config/routes.rb
> +      resources :users
Oh I See, Thanks very much for the insight @Meltrust, I have done exactly that to keep standard. :smile:

2023-01-21 12:08 UTC, Meltrust approved these changes
#### Hi @Alusp,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- All tests are passing now✔️ 
- Routes have been filtered to optimize performance, and to meet industry standards✔️ 
- Splendid job✔️ 



Cheers and Happy coding!👏👏👏


------

2023-01-21 12:10 UTC, Alusp commented
Thank very much @Meltrust for the review

2023-01-21 12:10 UTC, merged